joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0


teleop_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 1.25
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Right thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 3.0
    scale_angular_turbo:
      yaw: 4.5

    require_enable_button: true
    enable_button: 4  # Left shoulder button
    enable_turbo_button: 5  # Right shoulder button