scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -2.09      # Lower angular bound (in radians)
        upper_angle: 2.09       # Upper angular bound (in radians)
